GET http://localhost:5000/backend/test/ping
content-type: application/json

####
POST http://localhost:5000/backend/test/cache?id=1
content-type: application/json

{
    "test":"7464"
}

####
GET http://localhost:5000/backend/test/cache?id=1
content-type: application/json

testContent


###
POST 35.247.71.216:5000/ping
content-type: application/json